### ISSUE TITLE
(Test) Basic Test Suite

### ISSUE THREAD

**Issue by JeffBuss** [JeffBuss/gametime#27]

**Comment by sljohnson32** [comment]
Covers major functionality but not all added features.

**Comment by JeffBuss** [comment]
# **Test Objects**

### Ball
- is a function
- changes direction upon collision
- starts in center of paddle
- starts moving when enter is pressed

### Bricks
- brickArray defaults empty
- brickAlive defaults true
- adds a brick to column if brickColumns is > c
- adds a brick to row if brickColumns is > r
- has 4 rows and 8 columns made of bricks w/ width of 70 and height of 25

### Paddle
- moves right on right arrow
- moves left on left arrow
- has height of 20, width of 100, x position of (cw-100)/2, and y position of ch-20
