### ISSUE TITLE
(BF) Separate out business-logic and view-related code

### ISSUE THREAD

**Issue by sljohnson32** [JeffBuss/gametime#30]
This is spelled out in the rubric as an overall objective for the project. 

Update from 11/3 lesson: need to organize JS into separate object-oriented files for testing and organization.

**Comment by sljohnson32** [comment]
@JeffBuss along with collision/damage functionality, this is the big one we need to nail down ASAP.  

I am going to work on this now if you want to continue working on collision with the current markup - we can move it into whatever file we need to after but i think the functionality is critical to try and nail down before working about that.  Does that make sense?

If so, I'll create a new branch and start working.

**Comment by JeffBuss** [comment]
# **Test Objects**

### Ball
* is a function
* changes direction upon collision
* starts in center of paddle
* starts moving when enter is pressed

### Bricks

* brickArray defaults empty
* brickAlive defaults true
* adds a brick to column if brickColumns is > c
* adds a brick to row if brickColumns is > r
* has 4 rows and 8 columns made of bricks w/ width of 70 and height of 25

### Paddle
* moves right on right arrow
* moves left on left arrow
* has height of 20, width of 100, x position of (cw-100)/2, and y position of ch-20
